version: "3"

services:
  primary-db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
      - POSTGRES_DB=kong
      - POSTGRES_REPLICATION_MODE=master
    volumes:
      - primary-db-data:/var/lib/postgresql/data
    networks:
      - kong-net

#######################################
  # Kong database migration 1
#######################################
  kong-migration-1:
    image: kong:latest
    command: kong migrations bootstrap
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: primary-db
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    depends_on:
      - primary-db

  kong-1:
    container_name: kong-1
    image: kong:latest
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=primary-db
      - KONG_PG_PORT=5432
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PG_DATABASE=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    depends_on:
      - primary-db
    networks:
      - kong-net

  secondary-db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
      - POSTGRES_DB=kong
      - POSTGRES_REPLICATION_MODE=slave
    volumes:
      - secondary-db-data:/var/lib/postgresql/data
    networks:
      - kong-net

#######################################
  # Kong database migration 2
#######################################
  kong-migration-2:
    image: kong:latest
    command: kong migrations bootstrap
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: secondary-db
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    depends_on:
      - secondary-db

  kong-2:
    container_name: kong-2
    image: kong:latest
    ports:
      - "9000:8000"
      - "9001:8001"
      - "9443:8443"
      - "9444:8444"
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=secondary-db
      - KONG_PG_PORT=5432
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PG_DATABASE=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    depends_on:
      - secondary-db
    networks:
      - kong-net


  load-balancer:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - kong-1
      - kong-2
    networks:
      - kong-net

#######################################
  # Konga database prepare
#######################################
  konga-prepare:
    image: pantsel/konga:latest
    command: "-c prepare -a postgres -u postgresql://kong:${KONG_PG_PASSWORD:-kong}@primary-db:5432/konga"
    networks:
      - kong-net
    restart: on-failure
    depends_on:
      - primary-db

  konga:
    image: pantsel/konga:latest
    environment:
      - DB_ADAPTER=postgres
      - DB_HOST=primary-db
      - DB_USER=kong
      - DB_PASSWORD=kong
    ports:
      - '1337:1337'
    networks:
      - kong-net
    depends_on:
      - primary-db
      - konga-prepare

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/promtheus
    command:
     - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - kong-net
    restart: always

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    networks:
      - kong-net
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    networks:
      - kong-net      

volumes:
  primary-db-data:
  secondary-db-data:
  konga-database:
  prometheus_data:

networks:
  kong-net:
 